"""Default model configurations."""

from .models import ModelDefinition

DEFAULT_MODELS = [
    ModelDefinition(
        id="nanbeige-3b",
        name="Nanbeige 3B",
        description="Nanbeige 3B Q4_K_M - Fast, smart, 128K context (Primary)",
        filename_pattern=r"(?i)Nanbeige.*3B.*Q4_K_M.*\.gguf$",
        ctx_size=131072,
        n_gpu_layers=99,
        threads=8,
        batch_size=4096,
        ubatch_size=1024,
        temperature=0.6,
        top_p=0.95,
        flash_attn=True,
        mlock=True,
        mmap=False,
        cont_batching=True,
        priority=1,
        tags=["primary", "fast", "coding", "distilled"],
    ),
    ModelDefinition(
        id="qwen3-14b",
        name="Qwen3 14B",
        description="Qwen3 14B Q4_K_M - High quality, 8K context (Full VRAM)",
        filename_pattern=r"(?i)Qwen3-14B.*Q4_K_M.*\.gguf$",
        ctx_size=8192,
        n_gpu_layers=99,
        threads=8,
        batch_size=4096,
        ubatch_size=1024,
        temperature=0.6,
        top_p=0.95,
        flash_attn=True,
        mlock=True,
        mmap=False,
        cont_batching=True,
        priority=2,
        tags=["high-quality", "coding"],
    ),
    ModelDefinition(
        id="qwen2.5-7b",
        name="Qwen2.5 Coder 7B",
        description="Qwen2.5 Coder 7B Q5_K_M - Balanced, 128K context",
        filename_pattern=r"(?i)qwen2\.5-coder-7b.*Q5_K.*\.gguf$",
        ctx_size=131072,
        n_gpu_layers=99,
        threads=8,
        batch_size=4096,
        ubatch_size=1024,
        temperature=0.1,
        top_p=0.95,
        flash_attn=True,
        mlock=True,
        mmap=True,
        cont_batching=True,
        priority=3,
        tags=["balanced", "coding", "legacy"],
    ),
    ModelDefinition(
        id="qwen2.5-14b",
        name="Qwen2.5 Coder 14B",
        description="Qwen2.5 Coder 14B Q4_K_M - High quality, 64K context",
        filename_pattern=r"(?i)qwen2\.5-coder-14b.*Q4_K_M.*\.gguf$",
        ctx_size=65536,
        n_gpu_layers=99,
        threads=8,
        batch_size=4096,
        ubatch_size=1024,
        temperature=0.1,
        top_p=0.95,
        flash_attn=True,
        mlock=True,
        mmap=True,
        cont_batching=True,
        priority=4,
        tags=["high-quality", "coding", "legacy"],
    ),
]
